### ISSUE TITLE
Tokenization of SLICES strings and confusion with SMILES

### ISSUE THREAD

**Issue by sidnb13** [xiaohang007/SLICES#1]
Hello authors, thanks for open-sourcing this interesting work. I am interested in learning how SMILES strings can be tokenized for various language models. I was looking under `HTS` to understand how the RNN was trained on SLICES strings. However, all the code seems to be referring to SMILES strings. To clarify, is the code designed to operate on SMILES or SLICES data? Appreciate your clarification.

The paper states that the RNN is trained on SLICES strings, so I assume the approach here applies to that.

**Comment by xiaohang007** [comment]
Sorry for the confusion. I didn't rename all the SMILES to SLICES in the RNN codes. It actually works on SLICES. The tokenization function we used is just split(",") which is different from that of SMILES.
