### ISSUE TITLE
Cannot run Tutorial_2.1_MatterGPT_eform

### ISSUE THREAD

**Issue by funihang** [xiaohang007/SLICES#10]
Hi,
I’m encountering some issues with Tutorial 2.1 and wanted to ask if there might be something missing or incorrect. 
![image](https://github.com/user-attachments/assets/3b6f4697-e182-4cca-8824-20bb275eea2d)

Additionally, when I comment out the show_progress() function, it leads to another error
![image](https://github.com/user-attachments/assets/c9a881f2-62f2-41f5-aab3-e70c47fc9f98)
![image](https://github.com/user-attachments/assets/67433b9f-afaf-44c4-a13b-02bc430d14e5)

Could you please correct that? Thanks for your help.

**Comment by xiaohang007** [comment]
Thank you for identifying the bug. I've resolved it by adding the following lines to ./data/mp20_nonmetal/workflow/0_run.pbs:
"export PATH=/opt/conda/bin:$PATH
source activate chgnet"
This activates the chgnet environment for the data generation script, which I had forgotten to do initially. Now it's working perfectly.

**Comment by xiaohang007** [comment]
> Thank you for identifying the bug. I've resolved it by adding the following lines to ./data/mp20_nonmetal/workflow/0_run.pbs:
> "export PATH=/opt/conda/bin:$PATH
> source activate chgnet"
> This activates the chgnet environment for the data generation script, which I had forgotten to do initially. Now it's working perfectly.



> Hi, I’m encountering some issues with Tutorial 2.1 and wanted to ask if there might be something missing or incorrect. ![image](https://private-user-images.githubusercontent.com/55854600/361969252-3b6f4697-e182-4cca-8824-20bb275eea2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDMyMzcsIm5iZiI6MTcyNDgwMjkzNywicGF0aCI6Ii81NTg1NDYwMC8zNjE5NjkyNTItM2I2ZjQ2OTctZTE4Mi00Y2NhLTg4MjQtMjBiYjI3NWVlYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDIzNTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYmUxYTgyM2ZlYjg1N2EzMGNkYmRkYmRlZWI2ZDJmNjRiZTNhNjUzYjE5ZDhiMTE5MGI3NzRlYzkxMDRhY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ZnII1aDRW6uOZlj7wRy54NDPLcH_nyhlptGig1KMsk)
> 
> Additionally, when I comment out the show_progress() function, it leads to another error ![image](https://private-user-images.githubusercontent.com/55854600/361969563-c9a881f2-62f2-41f5-aab3-e70c47fc9f98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDMyMzcsIm5iZiI6MTcyNDgwMjkzNywicGF0aCI6Ii81NTg1NDYwMC8zNjE5Njk1NjMtYzlhODgxZjItNjJmMi00MWY1LWFhYjMtZTcwYzQ3ZmM5Zjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDIzNTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MmZkZjQ0NDdmMjUwZTllN2UyODU1NzBkNzExNWI0NmIwOWM5ZjI0NTEzM2Y4NTk0M2NjNzYzODNhMjA2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jspUmcw_GbctspX9DbeTxQU4d-H4XssYHhDKpbGhtP8) ![image](https://private-user-images.githubusercontent.com/55854600/361969657-67433b9f-afaf-44c4-a13b-02bc430d14e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDMyMzcsIm5iZiI6MTcyNDgwMjkzNywicGF0aCI6Ii81NTg1NDYwMC8zNjE5Njk2NTctNjc0MzNiOWYtYWZhZi00NGM0LWExM2ItMDJiYzQzMGQxNGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDIzNTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMDg0OThjYWY5YTM2M2QwMTViZGQ1M2IyMzkzYzQzMmIyYTk5ODc0NGY3MjA0Nzk0OTc5ZDhhNmNjODc5YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qVFc6MlPeBBasN7AL7EWdPWR0MHVYXaQY8dYAHD_fck)
> 
> Could you please correct that? Thanks for your help.

Thank you for identifying the bug. I've resolved it by adding the following lines to ./data/mp20_nonmetal/workflow/0_run.pbs:
"export PATH=/opt/conda/bin:$PATH
source activate chgnet"
This activates the chgnet environment for the data generation script, which I had forgotten to do initially. Now it's working perfectly.

**Comment by funihang** [comment]
Thank you for the update, but the issue in Tutorial 2.1 doesn't seem to be solved. The problem seems to originate in line 67 of the "1. building training set" cell, specifically with the `show_progress()` function. Additionally, even after commenting on this function, another error was reported. Lines 68 and 70 are cleaning up the data instead of collecting it. I guess there may be a need to modify the `utils.py` file to resolve this.

**Comment by xiaohang007** [comment]
> Thank you for the update, but the issue in Tutorial 2.1 doesn't seem to be solved. The problem seems to originate in line 67 of the "1. building training set" cell, specifically with the `show_progress()` function. Additionally, even after commenting on this function, another error was reported. Lines 68 and 70 are cleaning up the data instead of collecting it. I guess there may be a need to modify the `utils.py` file to resolve this.

I noticed that your conda location is ~/.conda, which indicates you're not using the provided Docker image. If you wish to run this tutorial on your own machine, you'll need to install not only SLICES but also the Slurm queue system to manage calculations, which can be a challenging task. I suggest you follow the steps below to setup the jupyter backend with the docker image provided.

Jupyter backend setup
(1) Download this repo and unzipped it.

(2) Put Materials Project's new API key in "APIKEY.ini".

(3) Edit "CPUs" in "slurm.conf" to set up the number of CPU threads available for the docker container.

(4) Run following commands in terminal (Linux or WSL2 Ubuntu on Win11)
```bash
# Download SLICES_docker with pre-installed SLICES and other relevant packages. 
docker pull xiaohang07/slices:v9  
# Make entrypoint_set_cpus.sh executable 
sudo chmod +x entrypoint_set_cpus_jupyter.sh
# Repalce "[]" with the absolute path of this repo's unzipped folder to setup share folder for the docker container.
docker run -it -p 8888:8888 -h workq  --shm-size=0.5gb --gpus all -v /[]:/crystal xiaohang07/slices:v9 /crystal/entrypoint_set_cpus_jupyter.sh
```

If you want to install slurm on your own machine, then follow these steps:
```bash
apt update \
&& apt install munge slurm-wlm slurm-wlm-doc slurm-wlm-torque -y \
&& rm -rf  /var/spool/slurm-llnl \
&& mkdir /var/spool/slurm-llnl \
&& chown -R slurm.slurm /var/spool/slurm-llnl \
&& rm -rf /var/run/slurm-llnl/ \
&& mkdir /var/run/slurm-llnl/ \
&& chown -R slurm.slurm /var/run/slurm-llnl/

#修改slurm.conf内容(改变cpu的数量，以及hostname到你的hostname)，然后
cp ./slurm.conf /etc/slurm-llnl/

service munge restart \
&& service slurmctld restart \
&& service slurmd restart
```
In addition, you should modify the 0_run.pbs files to fit your envs.

I have sent you a private message on linkedin with my wechat ID, BTW.
