### ISSUE TITLE
About the GPU-based hardware requirement to run this package.

### ISSUE THREAD

**Issue by hongyi-zhao** [xiaohang007/SLICES#11]
Hi,

I wonder what's the GPU-based hardware requirement to run this package. Any tips will be helpful.

Regards,
Zhao

**Comment by xiaohang007** [comment]
> Hi,
> 
> I wonder what's the GPU-based hardware requirement to run this package. Any tips will be helpful.
> 
> Regards, Zhao

For training MatterGPT models, a GPT-2 configuration with 12 layers, 12 attention heads, and a hidden size of 768, when trained on a bandgap dataset containing 280,000 data points, requires approximately 1-2 days of computation time using an NVIDIA RTX 4090 GPU. However, for running SLICES itself to encode and decode crystal structures, only CPU is needed.

**Comment by hongyi-zhao** [comment]
Thank you for your comments by providing the experience in model training. BTW, based on my personal understanding and knowledge, the 4090 is a gaming card, not a computing card. On the other hand, according to benchmark data from a research group at Westlake University, the 4090 is far from being the most cost-effective configuration:

![D9B580EAC044C1DB4774CB929C8F068C](https://github.com/user-attachments/assets/4325264f-b8f1-426f-b770-766c5c1976b9)

**Comment by xiaohang007** [comment]
> Thank you for your comments by providing the experience in model training. BTW, based on my understanding and knowledge, the 4090 is a gaming card, not a computing card. On the other hand, according to benchmark data from a research group at Westlake University, the 4090 is far from being the most cost-effective configuration:
> 
> ![D9B580EAC044C1DB4774CB929C8F068C](https://private-user-images.githubusercontent.com/11155854/362673118-4325264f-b8f1-426f-b770-766c5c1976b9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzMyNjMsIm5iZiI6MTcyNDkzMjk2MywicGF0aCI6Ii8xMTE1NTg1NC8zNjI2NzMxMTgtNDMyNTI2NGYtYjhmMS00MjZmLWI3NzAtNzY2YzVjMTk3NmI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEyMDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ODVhNjcxOWMxYTM4MGJiZDkxMjcwZjMwYzNkZTdkZDdjNDc3MWJmOWYxMTM0ODI5M2I4OGJmODM5Nzg4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3XK_18MYVRYLE2oLR314y0XDKWqdlOwIShYFbMm0Es)

Actually, some of the latest consumer-grade GPUs are surprisingly cost-effective for training large language models (with FP16 accuracy):
Certain high-end consumer GPUs (e.g. 4090) offer competitive FP16 computation power compared to some professional-grade GPUs (e.g. A100) that can cost several times more.
![未命名图片](https://github.com/user-attachments/assets/0b3a703b-4d3b-4606-81c6-55cb23ac29fd)
<img width="543" alt="未命名图片2" src="https://github.com/user-attachments/assets/477a495e-e8c7-404f-ad17-b0b7f25b3b74">

**Comment by hongyi-zhao** [comment]
I am currently considering the previously mentioned solution based on the NVIDIA TESLA V100 SXM2 8/4 card server as a configuration for the GPU machine, as shown below:

[高性能计算HPC_DTR-GS系列产品规格书_Rev1.1.pdf](https://github.com/user-attachments/files/16799376/HPC_DTR-GS._Rev1.1.pdf)
[达腾瑞HPC报价单_客户版.xlsx.zip](https://github.com/user-attachments/files/16799411/HPC._.xlsx.zip)

**Comment by xiaohang007** [comment]
> The price of 4090 is still relatively high. I am currently considering the previously mentioned solution based on the NVIDIA TESLA V100 SXM2 8/4 card server as a configuration for the GPU machine, as shown below:
> 
> [高性能计算HPC_DTR-GS系列产品规格书_Rev1.1.pdf](https://github.com/user-attachments/files/16799376/HPC_DTR-GS._Rev1.1.pdf) [达腾瑞HPC报价单_客户版.xlsx.zip](https://github.com/user-attachments/files/16799411/HPC._.xlsx.zip)

For large scale MD calculations, v100 is indeed a better choice than 4090.

**Comment by hongyi-zhao** [comment]
According to the description in the official brochure above, this configuration is suitable for various scenarios and performs well. So far, I have not had a chance to test it.

![image](https://github.com/user-attachments/assets/26ed3480-e746-4ad8-8033-753ad7c7fe65)

**Comment by hongyi-zhao** [comment]
> Actually, some of the latest consumer-grade GPUs are surprisingly cost-effective for training large language models (with FP16 accuracy):
> Certain high-end consumer GPUs (e.g. 4090) offer competitive FP16 computation power compared to some professional-grade GPUs (e.g. A100) that can cost several times more.

The series of products based on the Blackwell architecture also have similar issues: the FP32 and FP64 vector performance of a single B100 is 11% lower than that of the H100 SXM5, while a single B200 is 20% higher. It is estimated that the price of the B200 will be 3-4 times higher than that of the H100, making its cost-effectiveness in the field of scientific computing self-evident.

![3a6b8e6860dacf03267e140c41211a94_](https://github.com/user-attachments/assets/1877e4c1-4a04-4a78-8a97-ec09c3e00605)
![7a03c64fabf6110b41327f57c33642ce_](https://github.com/user-attachments/assets/53a82c82-327b-4eac-af47-22c12fef2976)

**Comment by xiaohang007** [comment]
> > Actually, some of the latest consumer-grade GPUs are surprisingly cost-effective for training large language models (with FP16 accuracy):
> > Certain high-end consumer GPUs (e.g. 4090) offer competitive FP16 computation power compared to some professional-grade GPUs (e.g. A100) that can cost several times more.
> 
> The series of products based on the Blackwell architecture also have similar issues: the FP32 and FP64 vector performance of a single B100 is 11% lower than that of the H100 SXM5, while a single B200 is 20% higher. It is estimated that the price of the B200 will be 3-4 times higher than that of the H100, making its cost-effectiveness in the field of scientific computing self-evident.
> 
> ![3a6b8e6860dacf03267e140c41211a94_](https://private-user-images.githubusercontent.com/11155854/362976167-1877e4c1-4a04-4a78-8a97-ec09c3e00605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODMwNDgsIm5iZiI6MTcyNDk4Mjc0OCwicGF0aCI6Ii8xMTE1NTg1NC8zNjI5NzYxNjctMTg3N2U0YzEtNGEwNC00YTc4LThhOTctZWMwOWMzZTAwNjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAxNTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZjU5NGQ3NDkzYmQ5MWZjM2Q1OTQxZmU0MGVhYzJlMTU4ODM0MmY3MmRiMWJkMTdkOTAzMzNmMTU5MjcxMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZooC7ZR2WBR5gvoTt1aXbqen-eypGf8lHbBlppLolug) ![7a03c64fabf6110b41327f57c33642ce_](https://private-user-images.githubusercontent.com/11155854/362976415-53a82c82-327b-4eac-af47-22c12fef2976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODMwNDgsIm5iZiI6MTcyNDk4Mjc0OCwicGF0aCI6Ii8xMTE1NTg1NC8zNjI5NzY0MTUtNTNhODJjODItMzI3Yi00ZWFjLWFmNDctMjJjMTJmZWYyOTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAxNTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwM2E3YzQ4MjNlOWI0NWQ1YjFjZTM3OTY2OGExZDQ3Y2Q1NDgzNTUzMDA5MTcwMDkwMDc0Y2I1MzAyOTgzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2KMi1mFewvY2FyreY18gdff9KWjYxPLEGkIYg2KA60)

Thank a lot for the valuable info. :)

**Comment by hongyi-zhao** [comment]
The fundamental reason for this phenomenon lies in profit motives: AI investments are more concentrated in the commercial sector rather than in HPC scientific computing. HPC scientific computing is relatively a niche field, as scientific research is an activity that only a very small number of people can engage in, and its actual output is unpredictable.

For companies like NVIDIA, if they truly want to support HPC, they only need to design specialized high-end HPC computing cards for specific world-class research institutions. This strategy is clearly the most wise and high-return.

This is exactly like the situation we see today with CPUs used in most research institutions: the so-called high-end CPUs used in the field of scientific research are often products discarded by major commercial companies.
