### ISSUE TITLE
Can this package be used to study nanocrystals?

### ISSUE THREAD

**Issue by hongyi-zhao** [xiaohang007/SLICES#12]
I'm not sure whether this package be used to study nanocrystals. Any hints/comments will be helpful.

Regards,
Zhao

**Comment by xiaohang007** [comment]
> I'm not sure whether this package be used to study nanocrystals. Any hints/comments will be helpful.
> 
> Regards, Zhao

Thank you for your inquiry about using our package to study nanocrystals. 
At present, SLICES does not support non-periodic nanocrystals. Our method is not yet capable of providing a comprehensive description of non-periodic systems. Although SMILES is good for non-periodic orgnaic molecules, it is also not suitable for describing nanocrystals.
I've been exploring an approach to describe nanoclusters (which are essentially small-scale nanocrystals) using principles similar to those in SLI2Cry. My research team and I have conducted preliminary investigations, experimenting with various layout algorithms to transform graph representations of nanoclusters into three-dimensional spatial arrangements.
We've encountered some difficulties with existing layout algorithms, such as those found in networkx and igraph (e.g., kk3d and other force-directed layouts). These algorithms, primarily designed for visualizing abstract graphs like social networks, prioritize visual representation over accurately reconstructing the original nanocluster structure encoded in the graph representation. The core limitation of these algorithms is their initial guesses are all randomly generated. 
We're currently searching for more suitable layout algorithms or considering the development of a high-precision algorithm tailored for nanoclusters. Despite the challenges, I'm optimistic about making progress in this area.
If you're interested in discussing this research direction further, I'd be happy to connect. You can reach me at [hangxiao@ln.edu.hk](mailto:hangxiao@ln.edu.hk). Please feel free to send me your WeChat information, and I'll add you so we can have a more detailed conversation.
