### ISSUE TITLE
Can't finish benchmark/Validity_rate_ucRNN__Success_rate_cRNN reproduction

### ISSUE THREAD

**Issue by Kirisame9961** [xiaohang007/SLICES#13]
Hi,
I’m encountering some issues with benchmark/Validity_rate_ucRNN_Success_rate_cRNN reproduction
it occurs from V1.4~2.0, I mainly tried on V1.4, using SLICE_docker_image_compressed.
After running former works, when running SLICES-1.4/benchmark/Validity_rate_ucRNN__Success_rate_cRNN/1_unconditioned_RNN/4_inverse/1_splitRun.py, not any result.csv was generated in job_* and  an empty results_4_inverse.csv was got after running 2_collect_clean_glob_details.py.
I tried to add some error output code and this is an example of 0_run.pbs.o:

![image](https://github.com/user-attachments/assets/150f3566-3604-4bdf-8e6a-ada447e9f531)

Processing SLICES string 1/28: Ce Ni Ni Sn Sn Ce Sn Ni Ni Ni Ni Sn Sn Sn 0 1 o - - 0 2 - o - 0 3 o o o 0 4 - o o 0 6 o - o 0 7 - - - 0 8 o - o 0 9 o o - 0 10 o o o 0 12 - o - 0 12 o o o 1 3 o + o 1 4 o + + 1 5 o o o 1 7 o o + 1 9 o o o 1 13 - o o 2 5 o - o 2 6 o - o 2 6 o o o 2 7 + o + 2 8 o o o 2 10 o o o 2 10 + o o 2 13 o o o 3 4 o o o 3 8 o - o 3 8 o o + 3 10 + o o 3 10 + o + 3 12 o - o 4 5 o - o 4 6 o - o 4 8 - - o 4 13 o o o 5 6 - o o 5 7 o o o 5 10 o o o 5 11 - o - 5 12 - o o 5 13 o o o 6 9 o + - 6 10 + o o 6 11 o o - 6 12 o o - 6 13 o o o 7 9 o o - 7 11 - o - 7 12 o o o 7 13 o o - 8 9 o + - 8 10 + o o 8 11 o o - 9 12 - - o 9 13 o o o 11 12 o o o 11 13 o o o 12 13 o o o 12 13 + o o
Successfully called from_SLICES. Proceeding to to_relaxed_structure...
Parameters passed to to_relaxed_structure:
bond_scaling=1.05, delta_theta=0.005, delta_x=0.45,
lattice_shrink=1.0, lattice_expand=1.25, angle_weight=0.5,
vbond_param_ave_covered=0.0, vbond_param_ave=0.01, repul=True
x_dat: [('1', '2', {'label': 'e1'}), ('1', '3', {'label': 'e2'}), ('1', '4', {'label': 'e3'}), ('1', '5', {'label': 'e4'}), ('1', '7', {'label': 'e5'}), ('1', '8', {'label': 'e6'}), ('1', '9', {'label': 'e7'}), ('1', '10', {'label': 'e8'}), ('1', '11', {'label': 'e9'}), ('1', '13', {'label': 'e10'}), ('1', '13', {'label': 'e11'}), ('2', '4', {'label': 'e12'}), ('2', '5', {'label': 'e13'}), ('2', '6', {'label': 'e14'}), ('2', '8', {'label': 'e15'}), ('2', '10', {'label': 'e16'}), ('2', '14', {'label': 'e17'}), ('3', '6', {'label': 'e18'}), ('3', '7', {'label': 'e19'}), ('3', '7', {'label': 'e20'}), ('3', '8', {'label': 'e21'}), ('3', '9', {'label': 'e22'}), ('3', '11', {'label': 'e23'}), ('3', '11', {'label': 'e24'}), ('3', '14', {'label': 'e25'}), ('4', '5', {'label': 'e26'}), ('4', '9', {'label': 'e27'}), ('4', '9', {'label': 'e28'}), ('4', '11', {'label': 'e29'}), ('4', '11', {'label': 'e30'}), ('4', '13', {'label': 'e31'}), ('5', '6', {'label': 'e32'}), ('5', '7', {'label': 'e33'}), ('5', '9', {'label': 'e34'}), ('5', '14', {'label': 'e35'}), ('6', '7', {'label': 'e36'}), ('6', '8', {'label': 'e37'}), ('6', '11', {'label': 'e38'}), ('6', '12', {'label': 'e39'}), ('6', '13', {'label': 'e40'}), ('6', '14', {'label': 'e41'}), ('7', '10', {'label': 'e42'}), ('7', '11', {'label': 'e43'}), ('7', '12', {'label': 'e44'}), ('7', '13', {'label': 'e45'}), ('7', '14', {'label': 'e46'}), ('8', '10', {'label': 'e47'}), ('8', '12', {'label': 'e48'}), ('8', '13', {'label': 'e49'}), ('8', '14', {'label': 'e50'}), ('9', '10', {'label': 'e51'}), ('9', '11', {'label': 'e52'}), ('9', '12', {'label': 'e53'}), ('10', '13', {'label': 'e54'}), ('10', '14', {'label': 'e55'}), ('12', '13', {'label': 'e56'}), ('12', '14', {'label': 'e57'}), ('13', '14', {'label': 'e58'}), ('13', '14', {'label': 'e59'})]
net_voltage: [[ 0 -1 -1]
 [-1  0 -1]
 [ 0  0  0]
 [-1  0  0]
 [ 0 -1  0]
 [-1 -1 -1]
 [ 0 -1  0]
 [ 0  0 -1]
 [ 0  0  0]
 [-1  0 -1]
 [ 0  0  0]
 [ 0  1  0]
 [ 0  1  1]
 [ 0  0  0]
 [ 0  0  1]
 [ 0  0  0]
 [-1  0  0]
 [ 0 -1  0]
 [ 0 -1  0]
 [ 0  0  0]
 [ 1  0  1]
 [ 0  0  0]
 [ 0  0  0]
 [ 1  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0 -1  0]
 [ 0  0  1]
 [ 1  0  0]
 [ 1  0  1]
 [ 0 -1  0]
 [ 0 -1  0]
 [ 0 -1  0]
 [-1 -1  0]
 [ 0  0  0]
 [-1  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [-1  0 -1]
 [-1  0  0]
 [ 0  0  0]
 [ 0  1 -1]
 [ 1  0  0]
 [ 0  0 -1]
 [ 0  0 -1]
 [ 0  0  0]
 [ 0  0 -1]
 [-1  0 -1]
 [ 0  0  0]
 [ 0  0 -1]
 [ 0  1 -1]
 [ 1  0  0]
 [ 0  0 -1]
 [-1 -1  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 1  0  0]]
Error processing SLICES string 1/28: Ce Ni Ni Sn Sn Ce Sn Ni Ni Ni Ni Sn Sn Sn 0 1 o - - 0 2 - o - 0 3 o o o 0 4 - o o 0 6 o - o 0 7 - - - 0 8 o - o 0 9 o o - 0 10 o o o 0 12 - o - 0 12 o o o 1 3 o + o 1 4 o + + 1 5 o o o 1 7 o o + 1 9 o o o 1 13 - o o 2 5 o - o 2 6 o - o 2 6 o o o 2 7 + o + 2 8 o o o 2 10 o o o 2 10 + o o 2 13 o o o 3 4 o o o 3 8 o - o 3 8 o o + 3 10 + o o 3 10 + o + 3 12 o - o 4 5 o - o 4 6 o - o 4 8 - - o 4 13 o o o 5 6 - o o 5 7 o o o 5 10 o o o 5 11 - o - 5 12 - o o 5 13 o o o 6 9 o + - 6 10 + o o 6 11 o o - 6 12 o o - 6 13 o o o 7 9 o o - 7 11 - o - 7 12 o o o 7 13 o o - 8 9 o + - 8 10 + o o 8 11 o o - 9 12 - - o 9 13 o o o 11 12 o o o 11 13 o o o 12 13 o o o 12 13 + o o
Exception type: TypeError
Exception details: cannot unpack non-iterable NoneType object

Here is script.py I have modified:
![image](https://github.com/user-attachments/assets/a6eb5518-a2ed-4c42-b9df-c53fadfd7278)

Could you please help? Thank you very much.

**Comment by xiaohang007** [comment]
> Hi, I’m encountering some issues with benchmark/Validity_rate_ucRNN_Success_rate_cRNN reproduction it occurs from V1.4~2.0, I mainly tried on V1.4, using SLICE_docker_image_compressed. After running former works, when running SLICES-1.4/benchmark/Validity_rate_ucRNN__Success_rate_cRNN/1_unconditioned_RNN/4_inverse/1_splitRun.py, not any result.csv was generated in job_* and an empty results_4_inverse.csv was got after running 2_collect_clean_glob_details.py. I tried to add some error output code and this is an example of 0_run.pbs.o:
> 
> ![image](https://private-user-images.githubusercontent.com/145451201/387992581-150f3566-3604-4bdf-8e6a-ada447e9f531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTczMTEsIm5iZiI6MTczMjA5NzAxMSwicGF0aCI6Ii8xNDU0NTEyMDEvMzg3OTkyNTgxLTE1MGYzNTY2LTM2MDQtNGJkZi04ZTZhLWFkYTQ0N2U5ZjUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxMDAzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2JkNjhjMDNhOTI4YzZiYTUxYjMxNTk3ZTM1NTA3NTYxN2JmMjYzOGY2NGNlMjg3ZDZkZmQ2OWNkYTE4MDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sYeLlsuPZ8PG-zBKNVXfIIQkdYn2YYQcr4gCpc61so0)
> 
> Processing SLICES string 1/28: Ce Ni Ni Sn Sn Ce Sn Ni Ni Ni Ni Sn Sn Sn 0 1 o - - 0 2 - o - 0 3 o o o 0 4 - o o 0 6 o - o 0 7 - - - 0 8 o - o 0 9 o o - 0 10 o o o 0 12 - o - 0 12 o o o 1 3 o + o 1 4 o + + 1 5 o o o 1 7 o o + 1 9 o o o 1 13 - o o 2 5 o - o 2 6 o - o 2 6 o o o 2 7 + o + 2 8 o o o 2 10 o o o 2 10 + o o 2 13 o o o 3 4 o o o 3 8 o - o 3 8 o o + 3 10 + o o 3 10 + o + 3 12 o - o 4 5 o - o 4 6 o - o 4 8 - - o 4 13 o o o 5 6 - o o 5 7 o o o 5 10 o o o 5 11 - o - 5 12 - o o 5 13 o o o 6 9 o + - 6 10 + o o 6 11 o o - 6 12 o o - 6 13 o o o 7 9 o o - 7 11 - o - 7 12 o o o 7 13 o o - 8 9 o + - 8 10 + o o 8 11 o o - 9 12 - - o 9 13 o o o 11 12 o o o 11 13 o o o 12 13 o o o 12 13 + o o Successfully called from_SLICES. Proceeding to to_relaxed_structure... Parameters passed to to_relaxed_structure: bond_scaling=1.05, delta_theta=0.005, delta_x=0.45, lattice_shrink=1.0, lattice_expand=1.25, angle_weight=0.5, vbond_param_ave_covered=0.0, vbond_param_ave=0.01, repul=True x_dat: [('1', '2', {'label': 'e1'}), ('1', '3', {'label': 'e2'}), ('1', '4', {'label': 'e3'}), ('1', '5', {'label': 'e4'}), ('1', '7', {'label': 'e5'}), ('1', '8', {'label': 'e6'}), ('1', '9', {'label': 'e7'}), ('1', '10', {'label': 'e8'}), ('1', '11', {'label': 'e9'}), ('1', '13', {'label': 'e10'}), ('1', '13', {'label': 'e11'}), ('2', '4', {'label': 'e12'}), ('2', '5', {'label': 'e13'}), ('2', '6', {'label': 'e14'}), ('2', '8', {'label': 'e15'}), ('2', '10', {'label': 'e16'}), ('2', '14', {'label': 'e17'}), ('3', '6', {'label': 'e18'}), ('3', '7', {'label': 'e19'}), ('3', '7', {'label': 'e20'}), ('3', '8', {'label': 'e21'}), ('3', '9', {'label': 'e22'}), ('3', '11', {'label': 'e23'}), ('3', '11', {'label': 'e24'}), ('3', '14', {'label': 'e25'}), ('4', '5', {'label': 'e26'}), ('4', '9', {'label': 'e27'}), ('4', '9', {'label': 'e28'}), ('4', '11', {'label': 'e29'}), ('4', '11', {'label': 'e30'}), ('4', '13', {'label': 'e31'}), ('5', '6', {'label': 'e32'}), ('5', '7', {'label': 'e33'}), ('5', '9', {'label': 'e34'}), ('5', '14', {'label': 'e35'}), ('6', '7', {'label': 'e36'}), ('6', '8', {'label': 'e37'}), ('6', '11', {'label': 'e38'}), ('6', '12', {'label': 'e39'}), ('6', '13', {'label': 'e40'}), ('6', '14', {'label': 'e41'}), ('7', '10', {'label': 'e42'}), ('7', '11', {'label': 'e43'}), ('7', '12', {'label': 'e44'}), ('7', '13', {'label': 'e45'}), ('7', '14', {'label': 'e46'}), ('8', '10', {'label': 'e47'}), ('8', '12', {'label': 'e48'}), ('8', '13', {'label': 'e49'}), ('8', '14', {'label': 'e50'}), ('9', '10', {'label': 'e51'}), ('9', '11', {'label': 'e52'}), ('9', '12', {'label': 'e53'}), ('10', '13', {'label': 'e54'}), ('10', '14', {'label': 'e55'}), ('12', '13', {'label': 'e56'}), ('12', '14', {'label': 'e57'}), ('13', '14', {'label': 'e58'}), ('13', '14', {'label': 'e59'})] net_voltage: [[ 0 -1 -1] [-1 0 -1] [ 0 0 0] [-1 0 0] [ 0 -1 0] [-1 -1 -1] [ 0 -1 0] [ 0 0 -1] [ 0 0 0] [-1 0 -1] [ 0 0 0] [ 0 1 0] [ 0 1 1] [ 0 0 0] [ 0 0 1] [ 0 0 0] [-1 0 0] [ 0 -1 0] [ 0 -1 0] [ 0 0 0] [ 1 0 1] [ 0 0 0] [ 0 0 0] [ 1 0 0] [ 0 0 0] [ 0 0 0] [ 0 -1 0] [ 0 0 1] [ 1 0 0] [ 1 0 1] [ 0 -1 0] [ 0 -1 0] [ 0 -1 0] [-1 -1 0] [ 0 0 0] [-1 0 0] [ 0 0 0] [ 0 0 0] [-1 0 -1] [-1 0 0] [ 0 0 0] [ 0 1 -1] [ 1 0 0] [ 0 0 -1] [ 0 0 -1] [ 0 0 0] [ 0 0 -1] [-1 0 -1] [ 0 0 0] [ 0 0 -1] [ 0 1 -1] [ 1 0 0] [ 0 0 -1] [-1 -1 0] [ 0 0 0] [ 0 0 0] [ 0 0 0] [ 0 0 0] [ 1 0 0]] Error processing SLICES string 1/28: Ce Ni Ni Sn Sn Ce Sn Ni Ni Ni Ni Sn Sn Sn 0 1 o - - 0 2 - o - 0 3 o o o 0 4 - o o 0 6 o - o 0 7 - - - 0 8 o - o 0 9 o o - 0 10 o o o 0 12 - o - 0 12 o o o 1 3 o + o 1 4 o + + 1 5 o o o 1 7 o o + 1 9 o o o 1 13 - o o 2 5 o - o 2 6 o - o 2 6 o o o 2 7 + o + 2 8 o o o 2 10 o o o 2 10 + o o 2 13 o o o 3 4 o o o 3 8 o - o 3 8 o o + 3 10 + o o 3 10 + o + 3 12 o - o 4 5 o - o 4 6 o - o 4 8 - - o 4 13 o o o 5 6 - o o 5 7 o o o 5 10 o o o 5 11 - o - 5 12 - o o 5 13 o o o 6 9 o + - 6 10 + o o 6 11 o o - 6 12 o o - 6 13 o o o 7 9 o o - 7 11 - o - 7 12 o o o 7 13 o o - 8 9 o + - 8 10 + o o 8 11 o o - 9 12 - - o 9 13 o o o 11 12 o o o 11 13 o o o 12 13 o o o 12 13 + o o Exception type: TypeError Exception details: cannot unpack non-iterable NoneType object
> 
> Here is script.py I have modified: ![image](https://private-user-images.githubusercontent.com/145451201/387992052-a6eb5518-a2ed-4c42-b9df-c53fadfd7278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTczMTEsIm5iZiI6MTczMjA5NzAxMSwicGF0aCI6Ii8xNDU0NTEyMDEvMzg3OTkyMDUyLWE2ZWI1NTE4LWEyZWQtNGM0Mi1iOWRmLWM1M2ZhZGZkNzI3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxMDAzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2YzYjdjZGY0YmJhOWMwNGFkOTcyMTYxMzE0NDFhMmNhMGVkYjdiZWM2MTA3YjQ1ZTViZmJiM2U5ODFjZGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PYHYqJviCDCWgmpz4EWDjapZDeeKGpwAHsV_PV_QwwE)
> 
> Could you please help? Thank you very much.

Could you show me the content of results in the "3_fix_syntax_check" folder?  You can send me a direct message on bilibili with your wechat ID, and I will show you how to solve this problem with wechat.
