### ISSUE TITLE
Build training sets fail (in Tutorial_2.1_MatterGPT_eform.ipynb)

### ISSUE THREAD

**Issue by 600DZY** [xiaohang007/SLICES#14]
We attempted to run the source code without relying on Docker, but the generated “mp20_eform_bandgap_nonmetal.csv” was empty. 

We traced back to the file "0_run.py" and found that the exception capture part in the code was not executed. Each job folder contains normal "temp.json" and "output.json", but lacks the "result.csv", which is the data source of the “mp20_eform_bandgap_nonmetal.csv”.

Would you like to help us analyze where the problem may lie? We confirmed that the execution of critical code was normal.
Or would you like to provide a few material_id to verify the exception capture?

Thanks a lot and looking forward to your reply.

**Comment by xiaohang007** [comment]
> We attempted to run the source code without relying on Docker, but the generated “mp20_eform_bandgap_nonmetal.csv” was empty.
> 
> We traced back to the file "0_run.py" and found that the exception capture part in the code was not executed. Each job folder contains normal "temp.json" and "output.json", but lacks the "result.csv", which is the data source of the “mp20_eform_bandgap_nonmetal.csv”.
> 
> Would you like to help us analyze where the problem may lie? We confirmed that the execution of critical code was normal. Or would you like to provide a few material_id to verify the exception capture?
> 
> Thanks a lot and looking forward to your reply.

You can send me a direct message on bilibili and we can set up a zoom meeting or tecent meeting to help you solve the problem. Or you can send me a email (hangxiao@ln.edu.hk) and we can set up the zoom meeting via email.

**Comment by 600DZY** [comment]
After discussing the issue with @xiaohang007 , it has been successfully resolved. Thanks a lot.
