### ISSUE TITLE
Error when I run on mac

### ISSUE THREAD

**Issue by suhasm** [xiaohang007/SLICES#4]
Hello,

This is really great work! Excited to use slices. When I try to run on mac, this line:

> reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)

Gives me the following error. Do you have any suggestions on what to do?

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[6], line 1
----> 1 reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)

File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1815, in InvCryRep.SLICES2structure(self, SLICES, strategy)
   1805 """Convert a SLICES string back to its original crystal structure.
   1806 
   1807 Args:
   (...)
   1812     float: Energy per atom predicted with M3GNet.
   1813 """
   1814 self.from_SLICES(SLICES,strategy)
-> 1815 structures,final_energy_per_atom = self.to_structures()
   1816 return structures[-1],final_energy_per_atom

File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1711, in InvCryRep.to_structures(self, bond_scaling, delta_theta, delta_x, lattice_shrink, lattice_expand, angle_weight, vbond_param_ave_covered, vbond_param_ave, repul)
   1709     inner_p_target, colattice_inds, colattice_weights = self.get_inner_p_target_debug(bond_scaling)
   1710 else:
-> 1711     inner_p_target, colattice_inds, colattice_weights = self.get_inner_p_target(bond_scaling)
   1712 uncovered_pair = self.get_uncovered_pair(net.graph)
   1713 uncovered_pair_lj = self.get_uncovered_pair_lj(uncovered_pair)

File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1128, in InvCryRep.get_inner_p_target(self, bond_scaling)
   1113 """ Get inner product matrix, colattice indices, colattice weights.
   1114 
   1115 (1) Get inner_p_target(inner_p matrix obtained by gfnff).
   (...)
   1125     list: Colattice weights.
   1126 """
   1127 nbf, blist = self.get_nbf_blist()
-> 1128 temp_dir = tempfile.TemporaryDirectory(dir="/dev/shm")
   1129 try:
   1130     with open(temp_dir.name+'/testBonds_cut.top','w') as f:

File ~/anaconda3/envs/htejk/lib/python3.11/tempfile.py:854, in TemporaryDirectory.__init__(self, suffix, prefix, dir, ignore_cleanup_errors)
    852 def __init__(self, suffix=None, prefix=None, dir=None,
    853              ignore_cleanup_errors=False):
--> 854     self.name = mkdtemp(suffix, prefix, dir)
    855     self._ignore_cleanup_errors = ignore_cleanup_errors
    856     self._finalizer = _weakref.finalize(
    857         self, self._cleanup, self.name,
    858         warn_message="Implicitly cleaning up {!r}".format(self),
    859         ignore_errors=self._ignore_cleanup_errors)

File ~/anaconda3/envs/htejk/lib/python3.11/tempfile.py:368, in mkdtemp(suffix, prefix, dir)
    366 _sys.audit("tempfile.mkdtemp", file)
    367 try:
--> 368     _os.mkdir(file, 0o700)
    369 except FileExistsError:
    370     continue    # try again

FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/tmpp6dvrbq7'

**Comment by xiaohang007** [comment]
Thank you for bringing this issue to my attention. It seems the error with the xtb_modified binary is likely due to it being compiled on Ubuntu, which causes compatibility problems when running it directly on MacOS.

A simple solution is to use our docker image on your Mac. You need to install the lastest version of SLICES on the docker container provided with "pip install slices" to get access to the latest version of it.

**Comment by xiaohang007** [comment]
> Hello,
> 
> This is really great work! Excited to use slices. When I try to run on mac, this line:
> 
> > reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)
> 
> Gives me the following error. Do you have any suggestions on what to do?
> 
> FileNotFoundError Traceback (most recent call last) Cell In[6], line 1 ----> 1 reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1815, in InvCryRep.SLICES2structure(self, SLICES, strategy) 1805 """Convert a SLICES string back to its original crystal structure. 1806 1807 Args: (...) 1812 float: Energy per atom predicted with M3GNet. 1813 """ 1814 self.from_SLICES(SLICES,strategy) -> 1815 structures,final_energy_per_atom = self.to_structures() 1816 return structures[-1],final_energy_per_atom
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1711, in InvCryRep.to_structures(self, bond_scaling, delta_theta, delta_x, lattice_shrink, lattice_expand, angle_weight, vbond_param_ave_covered, vbond_param_ave, repul) 1709 inner_p_target, colattice_inds, colattice_weights = self.get_inner_p_target_debug(bond_scaling) 1710 else: -> 1711 inner_p_target, colattice_inds, colattice_weights = self.get_inner_p_target(bond_scaling) 1712 uncovered_pair = self.get_uncovered_pair(net.graph) 1713 uncovered_pair_lj = self.get_uncovered_pair_lj(uncovered_pair)
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1128, in InvCryRep.get_inner_p_target(self, bond_scaling) 1113 """ Get inner product matrix, colattice indices, colattice weights. 1114 1115 (1) Get inner_p_target(inner_p matrix obtained by gfnff). (...) 1125 list: Colattice weights. 1126 """ 1127 nbf, blist = self.get_nbf_blist() -> 1128 temp_dir = tempfile.TemporaryDirectory(dir="/dev/shm") 1129 try: 1130 with open(temp_dir.name+'/testBonds_cut.top','w') as f:
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/tempfile.py:854, in TemporaryDirectory.**init**(self, suffix, prefix, dir, ignore_cleanup_errors) 852 def **init**(self, suffix=None, prefix=None, dir=None, 853 ignore_cleanup_errors=False): --> 854 self.name = mkdtemp(suffix, prefix, dir) 855 self._ignore_cleanup_errors = ignore_cleanup_errors 856 self._finalizer = _weakref.finalize( 857 self, self._cleanup, self.name, 858 warn_message="Implicitly cleaning up {!r}".format(self), 859 ignore_errors=self._ignore_cleanup_errors)
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/tempfile.py:368, in mkdtemp(suffix, prefix, dir) 366 _sys.audit("tempfile.mkdtemp", file) 367 try: --> 368 _os.mkdir(file, 0o700) 369 except FileExistsError: 370 continue # try again
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/tmpp6dvrbq7'

Thank you for bringing this issue to my attention. It seems the error is due to the [xtb_noring_nooutput_nostdout_noCN](https://github.com/xiaohang007/SLICES/blob/main/invcryrep/xtb_noring_nooutput_nostdout_noCN) binary was compiled on Ubuntu, which causes compatibility problems when running it directly on MacOS. Our reconstruction routine relies on xtb_noring_nooutput_nostdout_noCN to perform its second step: "Optimization of the non-barycentric embedding based on chemically meaningful geometry predicted with modified GFN-FF".

A simple solution is to use our docker image on your Mac.

**Comment by xiaohang007** [comment]
> Hello,
> 
> This is really great work! Excited to use slices. When I try to run on mac, this line:
> 
> > reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)
> 
> Gives me the following error. Do you have any suggestions on what to do?
> 
> FileNotFoundError Traceback (most recent call last) Cell In[6], line 1 ----> 1 reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1815, in InvCryRep.SLICES2structure(self, SLICES, strategy) 1805 """Convert a SLICES string back to its original crystal structure. 1806 1807 Args: (...) 1812 float: Energy per atom predicted with M3GNet. 1813 """ 1814 self.from_SLICES(SLICES,strategy) -> 1815 structures,final_energy_per_atom = self.to_structures() 1816 return structures[-1],final_energy_per_atom
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1711, in InvCryRep.to_structures(self, bond_scaling, delta_theta, delta_x, lattice_shrink, lattice_expand, angle_weight, vbond_param_ave_covered, vbond_param_ave, repul) 1709 inner_p_target, colattice_inds, colattice_weights = self.get_inner_p_target_debug(bond_scaling) 1710 else: -> 1711 inner_p_target, colattice_inds, colattice_weights = self.get_inner_p_target(bond_scaling) 1712 uncovered_pair = self.get_uncovered_pair(net.graph) 1713 uncovered_pair_lj = self.get_uncovered_pair_lj(uncovered_pair)
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/site-packages/invcryrep/invcryrep.py:1128, in InvCryRep.get_inner_p_target(self, bond_scaling) 1113 """ Get inner product matrix, colattice indices, colattice weights. 1114 1115 (1) Get inner_p_target(inner_p matrix obtained by gfnff). (...) 1125 list: Colattice weights. 1126 """ 1127 nbf, blist = self.get_nbf_blist() -> 1128 temp_dir = tempfile.TemporaryDirectory(dir="/dev/shm") 1129 try: 1130 with open(temp_dir.name+'/testBonds_cut.top','w') as f:
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/tempfile.py:854, in TemporaryDirectory.**init**(self, suffix, prefix, dir, ignore_cleanup_errors) 852 def **init**(self, suffix=None, prefix=None, dir=None, 853 ignore_cleanup_errors=False): --> 854 self.name = mkdtemp(suffix, prefix, dir) 855 self._ignore_cleanup_errors = ignore_cleanup_errors 856 self._finalizer = _weakref.finalize( 857 self, self._cleanup, self.name, 858 warn_message="Implicitly cleaning up {!r}".format(self), 859 ignore_errors=self._ignore_cleanup_errors)
> 
> File ~/anaconda3/envs/htejk/lib/python3.11/tempfile.py:368, in mkdtemp(suffix, prefix, dir) 366 _sys.audit("tempfile.mkdtemp", file) 367 try: --> 368 _os.mkdir(file, 0o700) 369 except FileExistsError: 370 continue # try again
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/tmpp6dvrbq7'

I tested running SLICES with the Docker image provided on my friend's Macbook Air M1, and it worked perfectly. However, I noticed that it took quite some time to complete the run. If you have any further questions or need assistance, please feel free to leave a message or contact me directly via email.
