### ISSUE TITLE
fail to load the backend

### ISSUE THREAD

**Issue by zcxzcx1** [xiaohang007/SLICES#7]
Hi, xiaohang. This is an great research and we want to using that to do some machine learning project to follow up. When I try to using SLICES following the tutorial, the install is success. But when I try to follow the examples, an error occur. Here is the command I use and the error massage, It seems that in the folder of models, no acceptable files format for the weights could be found. 
`from invcryrep.utils import temporaryWorkingDirectory

from invcryrep.invcryrep import InvCryRep

from pymatgen.core.structure import Structure

with temporaryWorkingDirectory("/home/zhudan/Desktop/chengxi/temp"):

    # obtaining the pymatgen Structure instance of NdSiRu

    original_structure = Structure.from_file(filename='/home/zhudan/Desktop/chengxi/test.cif')

    # creating an instance of the InvCryRep Class (initialization)

    backend=InvCryRep()

    # converting a crystal structure to its SLICES string

    slices_NdSiRu=backend.structure2SLICES(original_structure)

    # converting a SLICES string back to its original crystal structure and obtaining its M3GNet_IAP-predicted energy_per_atom

    reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)

    print('SLICES string of NdSiRu is: ',slices_NdSiRu)

    print('\nOriginal_structure is: ',original_structure)

    print('\nReconstructed_structure is: ',reconstructed_structure)

    print('\nfinal_energy_per_atom_IAP is: ',final_energy_per_atom_IAP,' eV/atom')` 

 `Traceback (most recent call last):
  File "/home/zhudan/Desktop/chengxi_mace/pythonProject/main.py", line 9, in <module>
    backend=InvCryRep()

  File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/invcryrep/invcryrep.py", line 112, in __init__
    self.relaxer = Relaxer(optimizer=optimizer)

  File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_dynamics.py", line 122, in __init__
    potential = Potential(M3GNet.load())

  File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_m3gnet.py", line 363, in load
    return cls.load(os.path.join(CWD, model_name))

  File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_m3gnet.py", line 367, in load
    return cls.from_dir(model_name)

  File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_m3gnet.py", line 336, in from_dir
    model.load_weights(model_name)

  File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 237, in load_weights
    raise ValueError(
ValueError: File format not supported: filepath=/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/MP-2021.2.8-EFS/m3gnet. Keras 3 only supports V3 `.keras` and `.weights.h5` files, or legacy V1/V2 `.h5` files.
` 
would you please help me?

**Comment by xiaohang007** [comment]
> Hi, xiaohang. This is an great research and we want to using that to do some machine learning project to follow up. When I try to using SLICES following the tutorial, the install is success. But when I try to follow the examples, an error occur. Here is the command I use and the error massage, It seems that in the folder of models, no acceptable files format for the weights could be found. `from invcryrep.utils import temporaryWorkingDirectory
> 
> from invcryrep.invcryrep import InvCryRep
> 
> from pymatgen.core.structure import Structure
> 
> with temporaryWorkingDirectory("/home/zhudan/Desktop/chengxi/temp"):
> 
> ```
> # obtaining the pymatgen Structure instance of NdSiRu
> 
> original_structure = Structure.from_file(filename='/home/zhudan/Desktop/chengxi/test.cif')
> 
> # creating an instance of the InvCryRep Class (initialization)
> 
> backend=InvCryRep()
> 
> # converting a crystal structure to its SLICES string
> 
> slices_NdSiRu=backend.structure2SLICES(original_structure)
> 
> # converting a SLICES string back to its original crystal structure and obtaining its M3GNet_IAP-predicted energy_per_atom
> 
> reconstructed_structure,final_energy_per_atom_IAP = backend.SLICES2structure(slices_NdSiRu)
> 
> print('SLICES string of NdSiRu is: ',slices_NdSiRu)
> 
> print('\nOriginal_structure is: ',original_structure)
> 
> print('\nReconstructed_structure is: ',reconstructed_structure)
> 
> print('\nfinal_energy_per_atom_IAP is: ',final_energy_per_atom_IAP,' eV/atom')` 
> ```
> 
> `Traceback (most recent call last): File "/home/zhudan/Desktop/chengxi_mace/pythonProject/main.py", line 9, in backend=InvCryRep()
> 
> File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/invcryrep/invcryrep.py", line 112, in **init** self.relaxer = Relaxer(optimizer=optimizer)
> 
> File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_dynamics.py", line 122, in **init** potential = Potential(M3GNet.load())
> 
> File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_m3gnet.py", line 363, in load return cls.load(os.path.join(CWD, model_name))
> 
> File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_m3gnet.py", line 367, in load return cls.from_dir(model_name)
> 
> File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/_m3gnet.py", line 336, in from_dir model.load_weights(model_name)
> 
> File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler raise e.with_traceback(filtered_tb) from None
> 
> File "/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 237, in load_weights raise ValueError( ValueError: File format not supported: filepath=/home/zhudan/miniconda3/envs/slices/lib/python3.9/site-packages/m3gnet/models/MP-2021.2.8-EFS/m3gnet. Keras 3 only supports V3 `.keras` and `.weights.h5` files, or legacy V1/V2 `.h5` files. ` would you please help me?

Thank you very much for your interest in SLICES. The problem occurs due to a newer version of TF/Keras is installed. I have updated the installation part of this repo, which should fix this issue. 

`conda create --name slices python=3.9`
`conda activate slices`
`pip install tensorflow==2.15.0 -i https://pypi.tuna.tsinghua.edu.cn/simple`
`pip install slices -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by zcxzcx1** [comment]
Thanks for your quick reply Xiaohang, the problem is solved.
