### ISSUE TITLE
Switch from `m3gnet` to `matgl`.

### ISSUE THREAD

**Issue by hongyi-zhao** [xiaohang007/SLICES#9]
[`M3gnet`](https://github.com/xiaohang007/SLICES/blob/6da5d686610cf6c43d2199251fba99fbf4bcac84/setup.py#L31) is used by this package currently, but as noted [here](https://github.com/materialsvirtuallab/m3gnet?tab=readme-ov-file):

> NOTE: A new implementation based on the Deep Graph Library and PyTorch called the [Materials Graph Library (MatGL)](https://github.com/materialsvirtuallab/matgl) has replaced this implementation. This repository has been archived and will no longer be maintained. It will be kept purely as a reference implementation. Users are recommended to use matgl instead.

So, it seems that we should use [`matgl`](https://github.com/materialsvirtuallab/matgl) instead.

Regards,
Zhao

**Comment by xiaohang007** [comment]
> [`m3gnet`](https://github.com/xiaohang007/SLICES/blob/6da5d686610cf6c43d2199251fba99fbf4bcac84/setup.py#L31) is used by this package currently, but as noted [here](https://github.com/materialsvirtuallab/m3gnet?tab=readme-ov-file):
> 
> > NOTE: A new implementation based on the Deep Graph Library and PyTorch called the [Materials Graph Library (MatGL)](https://github.com/materialsvirtuallab/matgl) has replaced this implementation. This repository has been archived and will no longer be maintained. It will be kept purely as a reference implementation. Users are recommended to use matgl instead.
> 
> So, it seems that we should use [`matgl`](https://github.com/materialsvirtuallab/matgl) instead.
> 
> Regards, Zhao

Thank you for your suggestion. I have conducted an internal test on SLICES with matgl, and it turned out to be around 10x slower than the CHGNet implementation in https://github.com/CederGroupHub/chgnet/tree/main/chgnet when running the benchmark of MP20, which is pretty weird.

**Comment by xiaohang007** [comment]
> [`m3gnet`](https://github.com/xiaohang007/SLICES/blob/6da5d686610cf6c43d2199251fba99fbf4bcac84/setup.py#L31) is used by this package currently, but as noted [here](https://github.com/materialsvirtuallab/m3gnet?tab=readme-ov-file):
> 
> > NOTE: A new implementation based on the Deep Graph Library and PyTorch called the [Materials Graph Library (MatGL)](https://github.com/materialsvirtuallab/matgl) has replaced this implementation. This repository has been archived and will no longer be maintained. It will be kept purely as a reference implementation. Users are recommended to use matgl instead.
> 
> So, it seems that we should use [`matgl`](https://github.com/materialsvirtuallab/matgl) instead.
> 
> Regards, Zhao

Do you think it is possible to integrate SLICES encoding and decoding in pymatgen, similar to the SMILES encoding and decoding functions in RDKIT?

**Comment by hongyi-zhao** [comment]
> Thank you for your suggestion. I have conducted an internal test on SLICES with matgl, and it turned out to be around 10x slower than the CHGNet implementation in https://github.com/CederGroupHub/chgnet/tree/main/chgnet when running the benchmark of MP20, which is pretty weird.

[matgl](https://github.com/materialsvirtuallab/matgl) is still under active development, perhaps you should commit a issue to discuss this problem with the developers in-depth to identify the bottleneck.

> Do you think it is possible to integrate SLICES encoding and decoding in pymatgen, similar to the SMILES encoding and decoding functions in RDKIT?

To be frank, I've no idea. But I also think that this is a wonderful idea and should be discussed with the pymatgen's core developer team.

**Comment by xiaohang007** [comment]
> > Thank you for your suggestion. I have conducted an internal test on SLICES with matgl, and it turned out to be around 10x slower than the CHGNet implementation in https://github.com/CederGroupHub/chgnet/tree/main/chgnet when running the benchmark of MP20, which is pretty weird.
> 
> [Matgl](https://github.com/materialsvirtuallab/matgl) is still under active development. Perhaps you should commit a issue to discuss this problem with the developers in-depth to identify the bottleneck.
> 
> > Do you think it is possible to integrate SLICES encoding and decoding in pymatgen, similar to the SMILES encoding and decoding functions in RDKIT?
> 
> To be frank, I've no idea. But I also think that this is a wonderful idea and should be discussed with the pymatgen's core developer team.

Thanks a lot. I will commit a issue to discuss this problem with the developers.
